#!/bin/bash
####################################################
# 1) use in terminal: 
#       $sh parse
# 2) dependencies:
#       parse.sed
#       join.awk
####################################################

chmod a+rx ./parse

WEBURL="https://leetcode.com/problemset/algorithms/"
WEBFILE="leetcode.html"
SED_SCRIPT="parse.sed"
AWK_SCRIPT="join.awk"
DEST="leetcode.tsv"

if !(test -s "$DEST")
then
    # crawl from leetcode algorithms page
    if !(test -s "$WEBFILE")
    then 
        curl "$WEBURL" > "$WEBFILE"
    fi    

    # parse webpage and generate csv file
    if !(test -s "$SED_SCRIPT")
    then
        echo "sed file not found!">&2
        exit 1
    fi
    if !(test -s "$AWK_SCRIPT")
    then
        echo "awk file not found!">&2
        exit 1
    fi
    sed -f "$SED_SCRIPT" "$WEBFILE" | awk -f "$AWK_SCRIPT" | sort -k1,1n > "$DEST"
fi

#clean up
#if (test -s "$WEBFILE")
#then
    #rm "$WEBFILE"
#fi

echo "Succeed! Check out file -> $DEST"
